/* Personal LinkedIn publishing + LinkedIn AI Studio */
(() => {
  const $ = id => document.getElementById(id);
  const esc = v => String(v ?? "").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"})[c]);
  async function json(response){const raw=await response.text();let body={};if(raw){try{body=JSON.parse(raw)}catch{throw new Error(`استجابة غير صالحة (HTTP ${response.status})`)}}if(!response.ok)throw new Error(body.detail||`HTTP ${response.status}`);return body}
  async function api(path,options={}){return json(await fetch(path,{headers:{"Content-Type":"application/json",...(options.headers||{})},...options}))}
  function prepareText(text){return String(text||"").replace(/\r\n?/g,"\n").replace(/[\u200e\u200f]/g,"")}
  function splitDataUrl(url){const m=String(url||"").match(/^data:(image\/(?:jpeg|png));base64,(.+)$/s);return m?{mime:m[1],b64:m[2]}:{mime:"image/jpeg",b64:""}}

  async function refreshStatus(){
    try{const s=await api("/api/linkedin/status");const box=$("liStatus");if(!box)return s;
      if(!s.configured){box.textContent="أضف متغيرات LinkedIn الثلاثة في Railway ثم أعد النشر.";$("liConnect")?.classList.add("hidden");return s}
      if(s.connected){box.className="li-status connected";box.textContent=`✓ متصل بالحساب: ${s.member_name||"LinkedIn"}`;$("liConnect")?.classList.add("hidden");$("liDisconnect")?.classList.remove("hidden")}
      else{box.className="li-status";box.textContent="الحساب غير متصل أو انتهت صلاحية التفويض.";$("liConnect")?.classList.remove("hidden");$("liDisconnect")?.classList.add("hidden")}
      return s;
    }catch(e){if($("liStatus"))$("liStatus").textContent=`تعذر قراءة الاتصال: ${e.message}`;return{connected:false}}
  }

  async function publish(text,imageData=[],studioPostId=""){
    const s=await refreshStatus();if(!s.connected){alert("اربط حساب LinkedIn أولًا من تبويب LinkedIn.");document.querySelector('[data-view="linkedin"]')?.click();return}
    const images=(Array.isArray(imageData)?imageData:imageData?[imageData]:[]).map(x=>typeof x==="string"?{data_url:x,alt_text:""}:x).filter(x=>x?.data_url).slice(0,20);
    const modal=document.createElement("div");modal.className="li-publish-modal";
    const previews=images.length?`<div class="li-publish-images">${images.map((x,i)=>`<figure class="li-publish-image"><img class="li-publish-preview" src="${esc(x.data_url)}"><figcaption>${i+1}. ${esc(x.alt_text||"صورة")}</figcaption></figure>`).join("")}</div>`:"<p>سيتم نشر النص بدون صورة.</p>";
    modal.innerHTML=`<div class="li-publish-card"><div class="section-title"><h3>معاينة منشور LinkedIn — النص النهائي</h3><button class="copy-btn" data-close>إغلاق</button></div>${previews}<label>راجع النص كاملًا قبل النشر <span id="liCharacterCount" class="counter"></span></label><textarea id="liPublishText" dir="rtl"></textarea><div class="row"><button class="action" id="liPublishConfirm">نشر الآن</button><button class="action secondary" data-close>إلغاء</button></div><div id="liPublishStatus" class="status"></div></div>`;
    document.body.appendChild(modal);$("liPublishText").value=String(text||"");
    const count=()=>{const n=prepareText($("liPublishText").value).length;$("liCharacterCount").textContent=`${n} / 3000`;$("liCharacterCount").style.color=n>3000?"#ff7777":""};$("liPublishText").oninput=count;count();
    modal.querySelectorAll("[data-close]").forEach(b=>b.onclick=()=>modal.remove());
    $("liPublishConfirm").onclick=async()=>{const btn=$("liPublishConfirm"),content=prepareText($("liPublishText").value.trim());if(!content)return $("liPublishStatus").textContent="النص مطلوب.";if(content.length>3000)return $("liPublishStatus").textContent="النص يتجاوز حد LinkedIn.";btn.disabled=true;$("liPublishStatus").textContent="جاري النشر...";try{const payloadImages=images.map(x=>{const p=splitDataUrl(x.data_url);return{image_b64:p.b64,image_mime_type:p.mime,alt_text:String(x.alt_text||"").slice(0,120)}});const r=await api("/api/linkedin/publish",{method:"POST",body:JSON.stringify({text:content,images:payloadImages,studio_post_id:studioPostId})});$("liPublishStatus").innerHTML=`تم النشر بنجاح. <a href="${esc(r.post_url)}" target="_blank">فتح المنشور</a>`;btn.textContent="✓ تم النشر";if(studioPostId){const s=state(),p=s.posts.find(x=>x.id===studioPostId);if(p){p.status="PUBLISHED";p.published_url=r.post_url;save(s);renderStudio()}}}catch(e){btn.disabled=false;$("liPublishStatus").textContent=`خطأ: ${e.message}`}}
  }
  window.cyberPulseLinkedIn={publish,refreshStatus};

  function initLinkedIn(){
    if($("linkedin"))return;const tabs=document.querySelector(".tabs"),wrap=document.querySelector(".wrap");if(!tabs||!wrap)return;
    const tab=document.createElement("button");tab.className="tab";tab.dataset.view="linkedin";tab.textContent="LinkedIn";tabs.insertBefore(tab,tabs.querySelector('[data-view="archive"]'));
    const section=document.createElement("section");section.id="linkedin";section.className="card hidden li-section";section.innerHTML=`<div class="section-title"><div><h2>LinkedIn الشخصي</h2><p>اربط حسابك مرة واحدة، ثم انشر بعد المعاينة.</p></div><span class="counter">OAuth 2.0</span></div><div id="liStatus" class="li-status">جاري التحقق...</div><div class="row"><a id="liConnect" class="action" href="/auth/linkedin/start">ربط حساب LinkedIn</a><button id="liDisconnect" class="action danger hidden">فصل الحساب</button></div>`;wrap.appendChild(section);
    tab.onclick=()=>{["studio","archive","news","visual-alert-editor","linkedin-ai-studio"].forEach(id=>$(id)?.classList.add("hidden"));section.classList.remove("hidden");document.querySelectorAll(".tab").forEach(b=>b.classList.toggle("active",b===tab));history.replaceState(null,"","#linkedin")};
    $("liDisconnect").onclick=async()=>{if(confirm("فصل حساب LinkedIn؟")){await api("/api/linkedin/disconnect",{method:"POST"});refreshStatus()}};refreshStatus();if(location.hash.startsWith("#linkedin")&&!location.hash.startsWith("#linkedin-ai-studio"))tab.click();
  }

  const STORAGE="cyberpulse_linkedin_ai_studio_v2";
  const MEDIA_DB="cyberpulse_linkedin_ai_media_v1",MEDIA_STORE="images",mediaCache=new Map();
  let mediaDbPromise=null;
  function openMediaDb(){
    if(!window.indexedDB)return Promise.resolve(null);
    if(mediaDbPromise)return mediaDbPromise;
    mediaDbPromise=new Promise((resolve,reject)=>{const request=indexedDB.open(MEDIA_DB,1);request.onupgradeneeded=()=>{if(!request.result.objectStoreNames.contains(MEDIA_STORE))request.result.createObjectStore(MEDIA_STORE)};request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error)}).catch(()=>null);
    return mediaDbPromise;
  }
  async function mediaGet(key){const db=await openMediaDb();if(!db)return null;return new Promise(resolve=>{const request=db.transaction(MEDIA_STORE,"readonly").objectStore(MEDIA_STORE).get(key);request.onsuccess=()=>resolve(request.result||null);request.onerror=()=>resolve(null)})}
  async function mediaPut(key,value){mediaCache.set(key,value);const db=await openMediaDb();if(!db)return false;return new Promise(resolve=>{const tx=db.transaction(MEDIA_STORE,"readwrite");tx.objectStore(MEDIA_STORE).put(value,key);tx.oncomplete=()=>resolve(true);tx.onerror=()=>resolve(false);tx.onabort=()=>resolve(false)})}
  async function mediaDelete(key){mediaCache.delete(key);const db=await openMediaDb();if(!db)return;await new Promise(resolve=>{const tx=db.transaction(MEDIA_STORE,"readwrite");tx.objectStore(MEDIA_STORE).delete(key);tx.oncomplete=resolve;tx.onerror=resolve;tx.onabort=resolve})}
  const WEEK_TWO=[
    {title:"وجود السياسات لا يعني أن برنامج الأمن السيبراني فعّال",brief:"اشرح لماذا لا تكفي السياسات وحدها لبناء برنامج أمن معلومات فعّال، وكيف تتحول الحوكمة من وثائق إلى مسؤوليات وقرارات وقياس مستمر.",cta:"اكتب «GRC» في التعليقات للحصول على تقييم نضج الحوكمة السيبرانية – 25 سؤالًا."},
    {title:"حالة عملية: سياسات كثيرة ومخاطر غير مرتبطة بالقرار",brief:"اعرض حالة مؤسسة لديها سياسات كثيرة، لكن المخاطر غير مرتبطة بأهداف المؤسسة ولا بمالكي المخاطر والقرارات الإدارية. اختم بسؤال: ما أول فجوة ستعالجها؟",cta:"ما أول فجوة ستعالجها في هذه الحالة؟ شاركني رأيك في التعليقات."},
    {title:"5 مخاطر قبل السماح للموظفين باستخدام أدوات الذكاء الاصطناعي",brief:"غطِّ مخاطر تسرب البيانات، Shadow AI، الملكية الفكرية، دقة المخرجات، والاعتماد على مزود خارجي، مع ضوابط عملية قبل السماح بالاستخدام.",cta:"اكتب «AI» في التعليقات للحصول على قائمة التحقق."},
    {title:"قيّم نضج الحوكمة السيبرانية في مؤسستك",brief:"قدّم Carousel عمليًا يشرح تقييم Cybersecurity GRC Maturity Assessment المكوّن من 25 سؤالًا عبر خمسة محاور: الحوكمة والمسؤوليات، إدارة المخاطر، السياسات والامتثال، القياس والتقارير، والتحسين المستمر. اذكر مستويات النتيجة: تأسيسي 0–39، نامٍ 40–59، مُدار 60–79، ناضج 80–100.",cta:"اكتب «GRC» في التعليقات وسأرسل لك ملف التقييم."}
  ];
  const PLAN=[
    ["أساسيات الحوكمة السيبرانية","كيف يتحول GRC من أوراق إلى قرارات إدارية؟","ما الذي يجب أن يراه مجلس الإدارة من الأمن السيبراني؟","Checklist: علامات ضعف برنامج GRC"],
    WEEK_TWO,
    ["ISO 27001 والتطبيق","لماذا لا تكفي شهادة ISO 27001 وحدها؟","Case Study: الفرق بين الامتثال والنضج","كيف تربط الضوابط بالمخاطر الفعلية؟","Checklist: ISO 27001 Gap Review"],
    ["مخاطر الموردين","Third-Party Risk: أين تبدأ المشكلة؟","Case Study: مورد صغير وتأثير كبير","AI vendors: ما الذي يجب أن تسأل عنه؟","Checklist: Third-Party Security Review"],
    ["القيادة السيبرانية","ما الذي يجب أن يطلبه CISO من الإدارة؟","Case Study: قرار Risk Acceptance غير موثق","Cyber metrics التي تهم الإدارة العليا","Checklist: Executive Cyber Dashboard"],
    ["AI Governance","من يملك مخاطر الذكاء الاصطناعي داخل المؤسسة؟","Case Study: رفع بيانات حساسة إلى أدوات AI","ISO 42001 من منظور عملي","Checklist: AI Governance Readiness"],
    ["إدارة الثغرات","CVSS العالي ليس المشكلة الوحيدة","Case Study: Patch موجود لكن الأصل مكشوف","كيف تربط Vulnerability Management بالمخاطر؟","Checklist: Vulnerability Governance"],
    ["الاستمرارية والمرونة","Cyber Resilience ليست Backup فقط","Case Study: انقطاع خدمة بسبب هجوم","BCP وIncident Response: أين يلتقيان؟","Checklist: Cyber Resilience Review"],
    ["الثقافة الأمنية","Awareness أم Security Culture؟","Case Study: لماذا لا يغير التدريب السلوك؟","كيف تقيس أثر التوعية؟","Checklist: Security Culture"],
    ["الخصوصية والبيانات","من يقرر ما الذي يمكن رفعه إلى AI؟","Case Study: مشاركة مستندات مع أدوات خارجية","Data Classification كأداة قرار","Checklist: AI/Data Sharing"],
    ["النضج والقياس","كيف تقيس نضج GRC بدون تعقيد؟","Case Study: KPI ممتاز وKRI مفقود","أهم مؤشرات المخاطر للإدارة","Checklist: GRC Maturity"],
    ["التحويل التجاري","7 علامات تحتاج معها GRC Health Check","Case Study: من الملاحظة إلى Roadmap","كيف تبني Cyber Risk Roadmap لـ90 يومًا؟","Checklist: Executive GRC Health Check"]
  ];
  let activePlan=PLAN,referencePlanPromise=null;
  async function loadReferencePlan(){
    if(referencePlanPromise)return referencePlanPromise;
    referencePlanPromise=api("/api/linkedin/reference-plan").then(plan=>{
      if(Array.isArray(plan.weeks)&&plan.weeks.length===12&&plan.weeks.every(w=>Array.isArray(w)&&w.length===4))activePlan=plan.weeks;
      return activePlan;
    }).catch(()=>activePlan);
    return referencePlanPromise;
  }
  const SLOTS=[{day:"الإثنين",pillar:"GRC / Governance",objective:"Authority",type:"Single Post"},{day:"الثلاثاء",pillar:"Case Study",objective:"Expertise",type:"Single Post"},{day:"الخميس",pillar:"AI / Cyber Risk",objective:"Reach",type:"Single Post"},{day:"السبت",pillar:"Checklist / Carousel",objective:"Leads",type:"Carousel"}];
  const state=()=>{try{return JSON.parse(localStorage.getItem(STORAGE))||{posts:[]}}catch{return{posts:[]}}};
  const syncTimers=new Map();
  function postPayload(p){return{id:p.id,week:p.week,day:p.day||"",pillar:p.pillar||"",objective:p.objective||"",post_type:p.type||"Single Post",title:p.title,status:p.status||"REVIEW",text:p.text||"",content:p.content||{},quality:p.quality||{}}}
  async function persistPost(p){return api("/api/linkedin/studio/posts",{method:"POST",body:JSON.stringify(postPayload(p))})}
  function schedulePersist(p){clearTimeout(syncTimers.get(p.id));syncTimers.set(p.id,setTimeout(()=>persistPost(p).catch(()=>{}),250))}
  function save(s){localStorage.setItem(STORAGE,JSON.stringify(s));(s.posts||[]).forEach(schedulePersist)}
  function anyDataUrl(url){const m=String(url||"").match(/^data:([^;]+);base64,(.+)$/s);return m?{mime:m[1],b64:m[2]}:{mime:"application/octet-stream",b64:""}}
  async function persistAsset(postId,asset){const raw=anyDataUrl(asset.data_url);if(!raw.b64)return;return api(`/api/linkedin/studio/posts/${encodeURIComponent(postId)}/assets`,{method:"POST",body:JSON.stringify({id:asset.id,kind:asset.kind||"image",name:asset.name||"",mime_type:raw.mime,data_b64:raw.b64,sort_order:asset.sort_order||0,alt_text:asset.alt_text||""})})}
  const calendarWeek=()=>Math.min(11,Math.max(0,Math.floor((new Date()-new Date(2026,7,24))/604800000)));
  let selectedWeek=calendarWeek();
  const week=()=>selectedWeek;
  const clean=v=>String(v??"").replace(/\r\n?/g,"\n").replace(/[\u200e\u200f]/g,"").trim();
  const tag=v=>{const t=clean(v).replace(/\s+/g,"");return t?(t.startsWith("#")?t:`#${t}`):""};

  function buildText(c){
    const hook=clean(c.hook||c.title),caption=clean(c.caption),rec=(c.recommendations||[]).map(clean).filter(Boolean).slice(0,5),cta=clean(c.cta),tags=(c.hashtags||[]).map(tag).filter(Boolean).slice(0,5);
    const ref=(c.sources||[]).find(x=>x?.name),sourceLine=ref&&!caption.includes(ref.name)?`المصدر المرجعي: ${ref.name}${ref.pages?` — الصفحات ${ref.pages}`:""}`:"";
    const suffix=[rec.length?`إجراءات عملية:\n${rec.map(x=>`• ${x}`).join("\n")}`:"",cta,sourceLine,tags.length?tags.join(" "):""].filter(Boolean).join("\n\n");
    const fixed=[hook,suffix].filter(Boolean).join("\n\n"),max=2980;
    let body=caption,allowance=Math.max(0,max-fixed.length-(hook&&suffix?4:2));
    if(body.length>allowance){body=body.slice(0,Math.max(0,allowance-1)).replace(/\s+\S*$/,"").trimEnd()+"…"}
    return [hook,body,suffix].filter(Boolean).join("\n\n").trim().slice(0,max)
  }

  const CAROUSEL_PERSONAL_VOICE=/(?:^|[\s،,:؛.!؟])(?:أرى|ارى|أعتقد|اعتقد|برأيي|في\s+رأيي|من\s+وجهة\s+نظري|بصفتي|كرئيس|كمدير|كمسؤول|كخبير|من\s+موقعي|من\s+خبرتي|أوصي|اوصي|نوصي|أؤكد|اؤكد)(?=$|[\s،,:؛.!؟])/i;
  function carouselVoiceIssues(c){const issues=[];(c?.slides||[]).forEach((slide,i)=>{for(const field of ["headline","body"]){if(CAROUSEL_PERSONAL_VOICE.test(clean(slide?.[field])))issues.push(`الشريحة ${i+1}`)}});return[...new Set(issues)]}
  function contentCheck(c,text=""){
    const missing=[];if(!clean(c.hook||c.title))missing.push("Hook");if(clean(c.caption).length<80)missing.push("المتن الكامل");if((c.recommendations||[]).filter(Boolean).length<3)missing.push("3 إجراءات عملية على الأقل");if(!clean(c.cta))missing.push("CTA");if((c.hashtags||[]).filter(Boolean).length<3)missing.push("3 هاشتاقات على الأقل");
    const rebuilt=buildText(c),current=clean(text),incomplete=current.length<Math.min(500,rebuilt.length*.65)||(rebuilt.includes("إجراءات عملية:")&&!current.includes("إجراءات عملية:"));return{missing,rebuilt,incomplete}
  }

  function score(c,t){const hook=Math.min(100,55+Math.min(35,String(c.hook||"").length)),authority=/إدارة|حوكمة|مخاطر|GRC|CISO|ISO|مجلس|قرار/i.test(t)?90:74,practical=(c.recommendations||[]).length>=3||/Checklist|قائمة|خطوات|إجراءات/i.test(t)?92:80,originality=/Case Study|من واقع|سيناريو|لماذا|كيف/i.test(t)?87:79,readability=t.length>=500&&t.length<=2200?92:t.length<=2800?84:76,commercial=/Health Check|Assessment|Workshop|Checklist|قائمة|تقييم/i.test(t)?84:68;return{hook,authority,practical_value:practical,originality,readability,commercial_intent:commercial,overall:Math.round((hook+authority+practical+originality+readability+commercial)/6)}}
  async function createPost(slot,topic,i){const spec=typeof topic==="string"?{title:topic,brief:"",cta:""}:topic,voice=slot.type==="Carousel"?"اكتب الشرائح كدليل عملي محايد: تعريفات وخطوات وقوائم تحقق وإرشادات مباشرة. امنع تمامًا صياغة الرأي أو السلطة الشخصية مثل: أرى، أعتقد، برأيي، بصفتي، كرئيس، كمدير، كمسؤول، أوصي، نوصي، أؤكد. لا تذكر منصب الكاتب داخل الشرائح.":"اكتب من منظور مسؤول أمن معلومات/حوكمة، برأي عملي واضح.";const instructions=[spec.title,spec.brief,spec.cta?`استخدم دعوة التفاعل التالية حرفيًا: ${spec.cta}`:"",voice,"اربط الموضوع بالقرار الإداري والمخاطر. يجب أن يتضمن الناتج Hook واضحًا، متنًا كاملًا، 3 إلى 5 إجراءات عملية، CTA، و3 إلى 5 هاشتاقات. لا تستخدم أرقامًا أو أخبارًا حديثة غير موثقة."].filter(Boolean).join(". ");const content=await api("/api/generate-content",{method:"POST",body:JSON.stringify({topic:instructions,domain:slot.pillar.includes("AI")?"AI Governance":slot.pillar.includes("Cyber")?"Cybersecurity":"GRC",post_type:slot.type,platform:"LinkedIn",audience:"UAE/GCC government and enterprise leaders and cybersecurity/GRC professionals",language:"Arabic",slides:slot.type==="Carousel"?6:1,tone:slot.type==="Carousel"?"Neutral practical field guide, objective and instructional":"Professional, practical, executive-friendly, CISO perspective",use_web_search:false,reference_week:week()+1,reference_slot:i+1})});if(spec.cta)content.cta=spec.cta;if(slot.type==="Carousel"&&carouselVoiceIssues(content).length)throw new Error("أعاد النموذج صياغة شخصية داخل الدليل؛ أعد المحاولة.");const text=buildText(content);return{id:`lai-${Date.now()}-${i}`,week:week()+1,day:slot.day,pillar:slot.pillar,objective:slot.objective,type:slot.type,title:spec.title,status:"REVIEW",text,content,quality:score(content,text),assets:[],visual_options:[],selected_visual:null}}

  const PEOPLE_POLICY="PEOPLE / ATTIRE REQUIREMENT: If any people appear, show either professionals in formal business attire or Emirati people in authentic UAE national dress. Emirati men must wear a clean white kandura with white ghutra and black agal. Emirati women must wear a modest black abaya with black shayla/headscarf covering the hair. Keep the styling contemporary, respectful, realistic and appropriate for UAE government/enterprise settings. Do not use casual clothing for Emirati subjects, uncovered hair for Emirati women, generic or inaccurate Gulf costumes, theatrical stereotypes, or mixed regional dress.";
  async function imageOption(post){const direction="EXECUTIVE EDITORIAL: realistic premium boardroom or executive decision-making scene. Show cyber risk and governance through leadership context, dashboards without readable text, realistic UAE/GCC enterprise setting where appropriate. Strong cinematic photography, restrained navy/cyan palette. No generic shields, gears, floating icons, stock infographic layouts, hacker clichés, pseudo text or clutter. One dominant focal scene. "+PEOPLE_POLICY;const r=await api("/api/generate-image",{method:"POST",body:JSON.stringify({title:post.title,body:`${post.content.hook||""}\n${post.content.caption||""}`.slice(0,1600),slide_number:1,post_type:"Single Post",domain:post.pillar.includes("AI")?"AI Governance":post.pillar.includes("Cyber")?"Cybersecurity":"GRC",visual_style:"Cyber Pulse",visual_direction:direction,variant_index:1})});return{data_url:`data:${r.mime_type||"image/jpeg"};base64,${r.b64_json}`,alt_text:post.title,label:"التصميم المقترح — Executive Editorial"}}

  const CAROUSEL={navy:"#06182D",navy2:"#0B2947",blue:"#0A84FF",cyan:"#00D1C7",ink:"#102B45",body:"#3E566E",paper:"#F6F9FC",line:"#DCE8F2",white:"#FFFFFF"};
  const carouselLogoCache={};
  function loadCarouselLogo(theme){if(carouselLogoCache[theme])return carouselLogoCache[theme];carouselLogoCache[theme]=new Promise(resolve=>{const img=new Image();img.onload=()=>resolve(img);img.onerror=()=>resolve(null);img.src=theme==="dark"?"cyberpulse-logo-dark.svg":"cyberpulse-logo-light.svg"});return carouselLogoCache[theme]}
  function rounded(ctx,x,y,w,h,r,fill,stroke="",lineWidth=1){ctx.beginPath();ctx.roundRect?.(x,y,w,h,r);if(!ctx.roundRect)ctx.rect(x,y,w,h);if(fill){ctx.fillStyle=fill;ctx.fill()}if(stroke){ctx.strokeStyle=stroke;ctx.lineWidth=lineWidth;ctx.stroke()}}
  function drawNetwork(ctx,originX,originY,color){ctx.save();ctx.globalAlpha=.22;ctx.strokeStyle=color;ctx.fillStyle=color;ctx.lineWidth=1.5;const nodes=[];for(let row=0;row<6;row++)for(let col=0;col<7;col++){const x=originX+col*92+(row%2)*34,y=originY+row*72+Math.sin((col+row)*1.7)*18;nodes.push({x,y});ctx.beginPath();ctx.arc(x,y,3.2,0,Math.PI*2);ctx.fill()}for(let i=0;i<nodes.length;i++){for(let j=i+1;j<nodes.length;j++){const dx=nodes[i].x-nodes[j].x,dy=nodes[i].y-nodes[j].y;if(dx*dx+dy*dy<12500){ctx.beginPath();ctx.moveTo(nodes[i].x,nodes[i].y);ctx.lineTo(nodes[j].x,nodes[j].y);ctx.stroke()}}}ctx.restore()}
  function drawProgress(ctx,index,total,dark=false){const gap=18,w=54,all=total*w+(total-1)*gap,start=(1080-all)/2;for(let i=0;i<total;i++){rounded(ctx,start+i*(w+gap),1274,w,7,4,i===index?CAROUSEL.cyan:(dark?"rgba(255,255,255,.22)":"#D4E1EB"))}}
  function fitLines(ctx,text,maxWidth,maxLines,startSize,minSize,weight=800){let size=startSize,lines=[];do{ctx.font=`${weight} ${size}px Cairo, Arial, sans-serif`;lines=wrap(ctx,text,maxWidth);if(lines.length<=maxLines)break;size-=2}while(size>=minSize);if(lines.length>maxLines){lines=lines.slice(0,maxLines);const last=lines.length-1;while(ctx.measureText(lines[last]+"…").width>maxWidth&&lines[last].includes(" "))lines[last]=lines[last].replace(/\s+\S+$/,"");lines[last]+="…"}return{size,lines}}
  function drawTextLines(ctx,lines,x,y,size,lineGap,color,weight=500){ctx.fillStyle=color;ctx.font=`${weight} ${size}px Cairo, Arial, sans-serif`;lines.forEach((line,i)=>ctx.fillText(line,x,y+i*(size+lineGap)))}
  function carouselLabel(post){return String(post.pillar||"GRC").split("/")[0].trim()||"GRC"}
  async function drawCarouselCover(ctx,post,slide,index,total){const bg=ctx.createLinearGradient(0,0,1080,1350);bg.addColorStop(0,CAROUSEL.navy);bg.addColorStop(1,"#0A3555");ctx.fillStyle=bg;ctx.fillRect(0,0,1080,1350);drawNetwork(ctx,540,55,CAROUSEL.cyan);ctx.fillStyle="rgba(0,209,199,.08)";ctx.beginPath();ctx.arc(90,1230,410,0,Math.PI*2);ctx.fill();const logo=await loadCarouselLogo("dark");if(logo)ctx.drawImage(logo,690,54,330,95);rounded(ctx,744,194,276,48,24,"rgba(0,209,199,.13)","rgba(0,209,199,.42)",1.5);ctx.direction="rtl";ctx.textAlign="center";ctx.fillStyle=CAROUSEL.cyan;ctx.font="700 23px Cairo, Arial";ctx.fillText(`${carouselLabel(post)}  •  دليل عملي`,882,227);ctx.textAlign="right";const title=slide.headline||post.title,fit=fitLines(ctx,title,900,4,78,54,800);drawTextLines(ctx,fit.lines,970,410,fit.size,24,CAROUSEL.white,800);ctx.fillStyle=CAROUSEL.cyan;ctx.fillRect(760,410+fit.lines.length*(fit.size+24)+8,210,6);const summary=String(slide.body||post.content.hook||"").trim(),bodyFit=fitLines(ctx,summary,820,4,34,28,500);drawTextLines(ctx,bodyFit.lines,970,575+fit.lines.length*72,bodyFit.size,18,"#D8E8F4",500);rounded(ctx,70,1128,380,92,46,"rgba(255,255,255,.08)","rgba(255,255,255,.18)");ctx.textAlign="center";ctx.fillStyle=CAROUSEL.white;ctx.font="600 25px Cairo, Arial";ctx.fillText("اسحب لقراءة الدليل",260,1185);ctx.fillStyle=CAROUSEL.cyan;ctx.font="700 34px Arial";ctx.fillText("←",105,1186);drawProgress(ctx,index,total,true)}
  async function drawCarouselBody(ctx,post,slide,index,total,isLast){ctx.fillStyle=CAROUSEL.paper;ctx.fillRect(0,0,1080,1350);ctx.fillStyle=CAROUSEL.navy;ctx.fillRect(0,0,1080,24);ctx.fillStyle=CAROUSEL.cyan;ctx.fillRect(0,24,1080,7);drawNetwork(ctx,-130,930,CAROUSEL.blue);const logo=await loadCarouselLogo("light");if(logo)ctx.drawImage(logo,738,48,282,81);ctx.direction="rtl";ctx.textAlign="right";rounded(ctx,70,72,210,50,25,"#E7F8F7");ctx.fillStyle="#087D80";ctx.font="700 22px Cairo, Arial";ctx.textAlign="center";ctx.fillText(`${carouselLabel(post)}  •  ${index+1}/${total}`,175,105);ctx.textAlign="right";rounded(ctx,884,174,126,126,30,CAROUSEL.navy);ctx.fillStyle=CAROUSEL.cyan;ctx.font="800 53px Cairo, Arial";ctx.textAlign="center";ctx.fillText(String(index+1).padStart(2,"0"),947,255);ctx.textAlign="right";const fit=fitLines(ctx,slide.headline||post.title,760,3,58,44,800);drawTextLines(ctx,fit.lines,834,205,fit.size,20,CAROUSEL.ink,800);ctx.fillStyle=CAROUSEL.blue;ctx.fillRect(704,205+fit.lines.length*(fit.size+20)+4,130,5);const cardY=Math.max(480,265+fit.lines.length*(fit.size+20));rounded(ctx,70,cardY,940,520,28,CAROUSEL.white,CAROUSEL.line,2);ctx.fillStyle=CAROUSEL.cyan;ctx.fillRect(980,cardY+38,7,444);ctx.fillStyle="#E8F6FF";ctx.beginPath();ctx.arc(902,cardY+92,39,0,Math.PI*2);ctx.fill();ctx.fillStyle=CAROUSEL.blue;ctx.font="800 28px Cairo, Arial";ctx.textAlign="center";ctx.fillText(isLast?"✓":"•",902,cardY+103);ctx.textAlign="right";const body=String(slide.body||"").trim(),bodyFit=fitLines(ctx,body,790,isLast?4:6,37,30,500);drawTextLines(ctx,bodyFit.lines,930,cardY+170,bodyFit.size,24,CAROUSEL.body,500);if(isLast&&post.content.cta){rounded(ctx,105,cardY+390,840,86,18,"#EAF8F7");ctx.fillStyle="#087D80";ctx.font="700 27px Cairo, Arial";ctx.textAlign="center";const ctaLines=wrap(ctx,post.content.cta,760).slice(0,2);ctaLines.forEach((line,i)=>ctx.fillText(line,525,cardY+438+i*36))}ctx.textAlign="right";ctx.fillStyle=CAROUSEL.ink;ctx.font="700 22px Cairo, Arial";ctx.fillText("نبض سيبراني",1000,1211);ctx.fillStyle="#6D8193";ctx.font="500 18px Cairo, Arial";ctx.fillText("معلومة موثوقة .. وحماية تبدأ بالوعي",1000,1242);ctx.textAlign="left";ctx.fillStyle="#6D8193";ctx.font="600 18px Arial";ctx.fillText("@cyberpulse_ar",70,1230);drawProgress(ctx,index,total,false)}
  async function renderCarousel(post){const voiceIssues=carouselVoiceIssues(post.content);if(voiceIssues.length)throw new Error(`الـCarousel يجب أن يكون دليلًا محايدًا. توجد صياغة شخصية في: ${voiceIssues.join("، ")}. استخدم «إعادة كتابة».`);if(document.fonts?.ready)await document.fonts.ready;try{await Promise.all([document.fonts.load("800 78px Cairo"),document.fonts.load("500 37px Cairo")])}catch{}const slides=post.content.slides||[],out=[];for(let i=0;i<slides.length;i++){const c=document.createElement("canvas");c.width=1080;c.height=1350;const ctx=c.getContext("2d");if(i===0)await drawCarouselCover(ctx,post,slides[i],i,slides.length);else await drawCarouselBody(ctx,post,slides[i],i,slides.length,i===slides.length-1);out.push({data_url:c.toDataURL("image/jpeg",.94),alt_text:`${post.title} — الشريحة ${i+1} من ${slides.length}`})}return out}
  window.cyberPulseCarousel={render:renderCarousel};
  function wrap(ctx,text,width){const paragraphs=String(text||"").split(/\n+/),lines=[];for(const paragraph of paragraphs){const words=paragraph.trim().split(/\s+/).filter(Boolean);let line="";for(const word of words){const test=line?`${line} ${word}`:word;if(ctx.measureText(test).width>width&&line){lines.push(line);line=word}else line=test}if(line)lines.push(line)}return lines}

  function visualHtml(post){if(post.type==="Carousel")return post.assets.length?`<div class="lai-carousel-grid">${post.assets.map((a,i)=>`<figure><img src="${esc(a.data_url)}"><figcaption>${i+1}/${post.assets.length}</figcaption></figure>`).join("")}</div>`:`<div class="lai-empty-visual">لا توجد صور بعد</div>`;const image=mediaCache.get(post.id)||post.visual_options?.find(a=>a.data_url);if(post.visual_options?.length&&image?.data_url)return `<div class="lai-options"><div class="lai-option selected"><img src="${esc(image.data_url)}"><strong>${esc(image.label||post.visual_options[0]?.label||"التصميم المقترح")}</strong><button class="action" data-select="0">✓ التصميم المختار</button></div></div>`;return`<div class="lai-empty-visual">اضغط «إنشاء تصميم» لعرض الصورة المقترحة</div>`}
  function postCard(p){const files=(p.supporting_files||[]).map(f=>`<a class="lai-file" href="/api/linkedin/studio/posts/${encodeURIComponent(p.id)}/assets/${encodeURIComponent(f.id)}/download">📎 ${esc(f.name)}</a>`).join(""),ref=(p.content?.sources||[]).find(x=>x?.name),reference=ref?`<div class="lai-reference"><strong>المصدر:</strong> ${esc(ref.name)}${ref.pages?` — الصفحات ${esc(ref.pages)}`:""}${ref.url?` · <a href="${esc(ref.url)}" target="_blank" rel="noopener">فتح مجلد المراجع</a>`:""}</div>`:"";const published=p.published_url?`<a href="${esc(p.published_url)}" target="_blank">فتح المنشور المنشور</a>`:"";return`<article class="lai-post" data-id="${esc(p.id)}"><div class="lai-post-head"><div><span class="lai-badge">${esc(p.day)}</span><span class="lai-badge">${esc(p.pillar)}</span><span class="lai-badge">${esc(p.objective)}</span></div><strong>${p.quality.overall}/100</strong></div><h3>${esc(p.title)}</h3>${reference}<textarea class="lai-text" dir="rtl">${esc(p.text)}</textarea><div class="lai-scores">Hook ${p.quality.hook} · Authority ${p.quality.authority} · Value ${p.quality.practical_value} · Readability ${p.quality.readability}</div><div class="lai-assets">${visualHtml(p)}</div><div class="lai-support"><strong>الملفات الداعمة المحفوظة</strong><div>${files||"لا توجد ملفات داعمة."}</div><div class="row"><button class="action" data-generate-support>توليد ملف داعم بنفس ثيم Carousel</button><label class="action secondary lai-upload">رفع ملف جاهز<input type="file" data-support hidden></label></div></div><div class="row"><button class="action" data-act="approve">${p.status==="APPROVED"||p.status==="PUBLISHED"?"✓ معتمد":"اعتماد المنشور"}</button><button class="action secondary" data-act="visual">${p.type==="Carousel"?(p.assets.length?"إعادة تصميم Carousel":"إنشاء Carousel"):(p.visual_options?.length?"إعادة توليد التصميم":"إنشاء تصميم")}</button><button class="action secondary" data-act="regenerate">إعادة كتابة</button><button class="action secondary" data-act="rebuild">إعادة تجهيز النص للنشر</button><button class="action secondary" data-act="publish" ${!['APPROVED','PUBLISHED'].includes(p.status)?"disabled":""}>معاينة ونشر</button><button class="action danger" data-act="reject">رفض</button></div><div class="status lai-post-status">${published}</div></article>`}
  async function hydrateMedia(posts,s){let compacted=false;for(const p of posts){const legacy=p.visual_options?.find(a=>a.data_url);if(legacy){await mediaPut(p.id,legacy);p.visual_options=[{alt_text:legacy.alt_text||p.title,label:legacy.label||"التصميم المقترح",media_key:p.id}];p.selected_visual=0;compacted=true}else if(p.visual_options?.length&&!mediaCache.has(p.id)){const stored=await mediaGet(p.id);if(stored)mediaCache.set(p.id,stored)}}if(compacted)save(s)}
  let databaseLoaded=false;
  async function loadStudioFromDatabase(){
    if(databaseLoaded)return;databaseLoaded=true;
    try{
      const remote=await api("/api/linkedin/studio/posts"),s=state(),localById=new Map((s.posts||[]).map(p=>[p.id,p]));
      for(const row of remote){if(!localById.has(row.id)){const p={...row,assets:[],visual_options:[],selected_visual:null,supporting_files:[]};s.posts.push(p);localById.set(p.id,p)}}
      for(const p of s.posts){
        await persistPost(p);
        const storedAssets=await api(`/api/linkedin/studio/posts/${encodeURIComponent(p.id)}/assets`);
        const images=storedAssets.filter(a=>a.kind==="image").map(a=>({id:a.id,data_url:`data:${a.mime_type};base64,${a.data_b64}`,alt_text:a.alt_text,name:a.name,sort_order:a.sort_order}));
        p.supporting_files=storedAssets.filter(a=>a.kind==="supporting_file").map(a=>({id:a.id,name:a.name,mime_type:a.mime_type,size:Math.round((a.data_b64||"").length*.75)}));
        if(images.length){if(p.type==="Carousel")p.assets=images;else{const image=images[0];await mediaPut(p.id,{data_url:image.data_url,alt_text:image.alt_text||p.title,label:"التصميم المحفوظ في PostgreSQL"});p.visual_options=[{alt_text:image.alt_text||p.title,label:"التصميم المحفوظ في PostgreSQL",media_key:p.id}];p.selected_visual=0}}
        else if(p.type==="Carousel"&&p.assets?.length){for(let i=0;i<p.assets.length;i++)await persistAsset(p.id,{...p.assets[i],id:`${p.id}-image-${i}`,kind:"image",name:`carousel-${i+1}.jpg`,sort_order:i})}
        else{const image=mediaCache.get(p.id)||await mediaGet(p.id);if(image?.data_url)await persistAsset(p.id,{...image,id:`${p.id}-image-main`,kind:"image",name:"design.jpg",sort_order:0})}
      }
      localStorage.setItem(STORAGE,JSON.stringify(s));await renderStudio();
    }catch(e){if($("laiStatus"))$("laiStatus").textContent=`تعذر تحميل الأرشيف المركزي: ${e.message}`}
  }
  async function renderStudio(){const s=state(),posts=s.posts.filter(p=>p.week===week()+1);if(!$("laiPosts"))return;await hydrateMedia(posts,s);$("laiWeek").textContent=`الأسبوع ${week()+1} من 12`;$("laiCount").textContent=`${posts.length}/4`;$("laiPosts").innerHTML=posts.length?posts.map(postCard).join(""):`<div class="empty">لم يتم توليد محتوى هذا الأسبوع بعد.</div>`;bindCards()}
  function bindCards(){document.querySelectorAll(".lai-post").forEach(card=>{const id=card.dataset.id,field=card.querySelector(".lai-text");field.onchange=()=>{const s=state(),p=s.posts.find(x=>x.id===id);p.text=field.value;p.quality=score(p.content,p.text);save(s);renderStudio()};card.querySelector("[data-support]").onchange=e=>uploadSupportingFile(id,e.target.files?.[0],card);card.querySelector("[data-generate-support]").onclick=()=>generateSupportingFile(id,card);card.querySelectorAll("[data-select]").forEach(b=>b.onclick=()=>{const s=state(),p=s.posts.find(x=>x.id===id),idx=Number(b.dataset.select);if(!p?.visual_options?.[idx])return;p.selected_visual=idx;p.assets=[];save(s);renderStudio()});card.querySelectorAll("[data-act]").forEach(b=>b.onclick=()=>act(id,b.dataset.act,card))})}

  async function generateSupportingFile(postId,card){const button=card.querySelector("[data-generate-support]"),status=card.querySelector(".lai-post-status");button.disabled=true;status.textContent="جاري إعداد الدليل وتصميمه بنفس هوية Carousel...";try{const result=await api(`/api/linkedin/studio/posts/${encodeURIComponent(postId)}/supporting-file/generate`,{method:"POST",body:JSON.stringify({file_type:"دليل عملي"})}),s=state(),p=s.posts.find(x=>x.id===postId);p.supporting_files=[...(p.supporting_files||[]),{id:result.id,name:result.name,mime_type:result.mime_type,size:result.size}];localStorage.setItem(STORAGE,JSON.stringify(s));status.textContent=`تم إنشاء ملف PDF من ${result.pages} صفحات وحفظه في PostgreSQL.`;await renderStudio()}catch(e){status.textContent=`خطأ: ${e.message}`}finally{button.disabled=false}}

  async function uploadSupportingFile(postId,file,card){if(!file)return;const status=card.querySelector(".lai-post-status");if(file.size>20*1024*1024){status.textContent="خطأ: حجم الملف الداعم يتجاوز 20 MB.";return}status.textContent="جاري حفظ الملف الداعم في PostgreSQL...";try{const dataUrl=await new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=()=>reject(new Error("تعذر قراءة الملف"));r.readAsDataURL(file)}),asset={id:`${postId}-support-${Date.now()}`,kind:"supporting_file",name:file.name,mime_type:file.type||"application/octet-stream",data_url:dataUrl,sort_order:0};await persistAsset(postId,asset);const s=state(),p=s.posts.find(x=>x.id===postId);p.supporting_files=[...(p.supporting_files||[]),{id:asset.id,name:file.name,mime_type:asset.mime_type,size:file.size}];localStorage.setItem(STORAGE,JSON.stringify(s));status.textContent="تم حفظ الملف الداعم في PostgreSQL.";renderStudio()}catch(e){status.textContent=`خطأ: ${e.message}`}}

  async function act(id,action,card){const s=state(),p=s.posts.find(x=>x.id===id),status=card.querySelector(".lai-post-status");try{
    if(action==="approve"){p.status="APPROVED";save(s);renderStudio();return}
    if(action==="reject"){p.status="REJECTED";save(s);renderStudio();return}
    if(action==="visual"){if(p.type==="Carousel"){status.textContent="جاري إنشاء Carousel...";p.assets=await renderCarousel(p);await persistPost(p);for(let i=0;i<p.assets.length;i++)await persistAsset(p.id,{...p.assets[i],id:`${p.id}-image-${i}`,kind:"image",name:`carousel-${i+1}.jpg`,sort_order:i})}else{status.textContent="جاري إنشاء التصميم...";const image=await imageOption(p);await mediaPut(p.id,image);p.visual_options=[{alt_text:image.alt_text,label:image.label,media_key:p.id}];p.selected_visual=0;p.assets=[];await persistPost(p);await persistAsset(p.id,{...image,id:`${p.id}-image-main`,kind:"image",name:"design.jpg",sort_order:0})}save(s);renderStudio();return}
    if(action==="regenerate"){status.textContent="جاري إعادة الكتابة من المرجع نفسه...";await loadReferencePlan();const slotIndex=Math.max(0,SLOTS.findIndex(x=>x.day===p.day)),slot=SLOTS[slotIndex],topic=activePlan[p.week-1]?.[slotIndex]||p.title,r=await createPost(slot,topic,slotIndex);p.title=r.title;p.content=r.content;p.text=r.text;p.quality=r.quality;p.status="REVIEW";p.assets=[];p.visual_options=[];p.selected_visual=null;save(s);renderStudio();return}
    if(action==="rebuild"){const check=contentCheck(p.content,p.text);if(check.missing.length)throw new Error(`المحتوى الأصلي ناقص: ${check.missing.join("، ")}. استخدم «إعادة كتابة».`);p.text=check.rebuilt;p.quality=score(p.content,p.text);save(s);renderStudio();return}
    if(action==="publish"){
      if(p.status!=="APPROVED")throw new Error("اعتمد المنشور أولًا.");
      if(p.type==="Carousel"){const voiceIssues=carouselVoiceIssues(p.content);if(voiceIssues.length)throw new Error(`تم إيقاف النشر: الـCarousel دليل محايد ولا يقبل صياغة شخصية. راجع ${voiceIssues.join("، ")} أو استخدم «إعادة كتابة».`)}
      const check=contentCheck(p.content,p.text);if(check.missing.length)throw new Error(`تم إيقاف النشر لأن المحتوى ناقص: ${check.missing.join("، ")}. استخدم «إعادة كتابة».`);
      if(check.incomplete){p.text=check.rebuilt;p.quality=score(p.content,p.text);save(s);status.textContent=`تم اكتشاف نص ناقص وإعادة تجهيزه تلقائيًا — ${p.text.length} حرف. اضغط «معاينة ونشر» مرة أخرى لمراجعة النص الكامل.`;const field=card.querySelector(".lai-text");if(field)field.value=p.text;return}
      if(p.type==="Carousel"){if(!p.assets.length)throw new Error("أنشئ الـCarousel أولًا.");await publish(p.text,p.assets,p.id);return}
      const chosen=mediaCache.get(p.id)||await mediaGet(p.id)||p.visual_options?.find(x=>x.data_url);if(!chosen?.data_url)throw new Error("أنشئ التصميم أولًا.");mediaCache.set(p.id,chosen);await publish(p.text,[chosen],p.id);
    }
  }catch(e){status.textContent=`خطأ: ${e.message}`}}

  async function generateWeek(){const btn=$("laiGenerate"),msg=$("laiStatus"),w=week();btn.disabled=true;try{await loadReferencePlan();const topics=activePlan[w];const s=state();const previous=s.posts.filter(p=>p.week===w+1);if(previous.length&&!confirm("يوجد محتوى لهذا الأسبوع. هل تريد استبداله؟"))return;for(const post of previous){await mediaDelete(post.id);await api(`/api/linkedin/studio/posts/${encodeURIComponent(post.id)}`,{method:"DELETE"})}s.posts=s.posts.filter(p=>p.week!==w+1);save(s);for(let i=0;i<4;i++){msg.textContent=`جاري إنشاء المنشور ${i+1} من 4 من الملفات المرجعية...`;const p=await createPost(SLOTS[i],topics[i],i),fresh=state();fresh.posts.push(p);save(fresh);await persistPost(p);renderStudio()}msg.textContent="اكتمل تجهيز محتوى الأسبوع من الملفات المرجعية وحُفظ في PostgreSQL. راجع النص والمصدر والتصميم ثم اعتمد قبل النشر."}catch(e){msg.textContent=`خطأ: ${e.message}`}finally{btn.disabled=false}}

  function initStudio(){if($("linkedin-ai-studio"))return;const tabs=document.querySelector(".tabs"),wrapEl=document.querySelector(".wrap");if(!tabs||!wrapEl)return;const tab=document.createElement("button");tab.className="tab";tab.dataset.view="linkedin-ai-studio";tab.textContent="LinkedIn AI Studio";tabs.insertBefore(tab,tabs.querySelector('[data-view="archive"]'));const sec=document.createElement("section");sec.id="linkedin-ai-studio";sec.className="card hidden";sec.innerHTML=`<div class="section-title"><div><h2>LinkedIn AI Studio</h2><p>48 موضوعًا مستندًا إلى 7 مراجع → توليد → مراجعة المصدر → اعتماد → نشر.</p></div><span id="laiWeek" class="counter"></span></div><div class="lai-strategy"><div><strong>المراجع</strong><p>ISO 27001/27002 + GRC + Risk + Audit + CISSP + التحقيقات</p></div><div><strong>الصور</strong><p>تصميم واحد: Executive Editorial</p></div><div><strong>فحص النشر</strong><p>Hook + متن + إجراءات + CTA + مصدر وصفحات</p></div></div><div class="row lai-week-controls"><label>اختر الأسبوع <select id="laiWeekSelect">${PLAN.map((_,i)=>`<option value="${i}">الأسبوع ${i+1}</option>`).join("")}</select></label><button id="laiGenerate" class="action">توليد محتوى الأسبوع من المراجع</button><span id="laiCount" class="counter">0/4</span></div><div id="laiStatus" class="status"></div><div id="laiPosts" class="lai-posts"></div>`;wrapEl.appendChild(sec);$("laiWeekSelect").value=String(selectedWeek);$("laiWeekSelect").onchange=e=>{selectedWeek=Number(e.target.value);$("laiStatus").textContent=`تم اختيار الأسبوع ${selectedWeek+1} من خطة الملفات المرجعية.`;renderStudio()};tab.onclick=()=>{["studio","archive","news","visual-alert-editor","linkedin"].forEach(id=>$(id)?.classList.add("hidden"));sec.classList.remove("hidden");document.querySelectorAll(".tab").forEach(b=>b.classList.toggle("active",b===tab));history.replaceState(null,"","#linkedin-ai-studio");renderStudio()};document.querySelectorAll('.tab:not([data-view="linkedin-ai-studio"])').forEach(b=>b.addEventListener("click",()=>sec.classList.add("hidden")));$("laiGenerate").onclick=generateWeek;if(location.hash.startsWith("#linkedin-ai-studio"))tab.click();else renderStudio()}
  function injectStyles(){const s=document.createElement("style");s.textContent=`.li-section{max-width:820px;margin:auto}.li-status{margin:18px 0;padding:14px;border:1px solid #294760;border-radius:12px;background:#081827}.li-status.connected{border-color:#1bd3cf;color:#77f2ee}.li-publish-modal{position:fixed;inset:0;z-index:9999;background:#020914d9;display:flex;align-items:center;justify-content:center;padding:18px}.li-publish-card{width:min(760px,100%);max-height:90vh;overflow:auto;background:#0d1a2b;border:1px solid #294760;border-radius:18px;padding:18px;direction:rtl}.li-publish-card textarea{min-height:340px;direction:rtl;line-height:1.8}.li-publish-images{display:grid;grid-template-columns:repeat(auto-fit,minmax(105px,1fr));gap:9px}.li-publish-preview{width:100%;max-height:240px;object-fit:contain}.lai-strategy{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;margin:15px 0}.lai-strategy>div,.lai-post{background:#091625;border:1px solid #294760;border-radius:14px;padding:14px}.lai-strategy p,.lai-scores{color:#9eb2c9}.lai-posts{display:grid;gap:16px;margin-top:18px}.lai-post-head{display:flex;justify-content:space-between}.lai-badge{display:inline-block;background:#10283a;color:#77f2ee;border-radius:999px;padding:4px 8px;margin-left:5px;font-size:.78rem}.lai-reference{margin:8px 0 12px;padding:9px 11px;border-right:3px solid #1bd3cf;background:#0c2032;color:#bcd0e3;border-radius:8px}.lai-reference a{color:#67e4ff}.lai-text{min-height:250px;line-height:1.8}.lai-assets{margin:12px 0}.lai-options{display:grid;grid-template-columns:1fr;gap:14px;max-width:520px}.lai-option{padding:10px;border:1px solid #294760;border-radius:14px;display:grid;gap:8px}.lai-option.selected{border-color:#1bd3cf;box-shadow:0 0 0 2px #1bd3cf33}.lai-option img{width:100%;aspect-ratio:4/5;object-fit:cover;border-radius:10px}.lai-carousel-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px}.lai-carousel-grid figure{position:relative;margin:0}.lai-carousel-grid img{display:block;width:100%;aspect-ratio:4/5;object-fit:cover;border-radius:12px;border:1px solid #294760}.lai-carousel-grid figcaption{position:absolute;left:10px;bottom:10px;padding:4px 8px;border-radius:999px;background:#06182de6;color:#77f2ee;font:700 12px Cairo}.lai-empty-visual{padding:28px;border:1px dashed #294760;border-radius:10px;color:#9eb2c9;text-align:center}.lai-support{display:grid;gap:8px;margin:12px 0;padding:12px;border:1px solid #294760;border-radius:10px}.lai-file{display:inline-block;margin:4px;padding:5px 8px;background:#10283a;border-radius:8px}.lai-upload{display:inline-block;width:max-content;cursor:pointer}@media(max-width:800px){.lai-strategy,.lai-options{grid-template-columns:1fr}}@media(max-width:560px){.lai-carousel-grid{grid-template-columns:1fr}}`;document.head.appendChild(s)}
  function start(){injectStyles();initLinkedIn();initStudio();loadReferencePlan();loadStudioFromDatabase()}
  if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",start);else start();
})();
